- DSC 530
- Week 5 and 6
- Rethish Plappuzha Sreedharan Nair

In [43]:
# Importing the required libraries
import pandas as pd

# Exercise 1.

With the earthquakes.csv file, select all the earthquakes in Japan with a magnitude of 4.9 or greater using the mb magnitude type.

In [44]:
# Reading the earthquakes dataset
df_earthquakes = pd.read_csv('earthquakes.csv')
df_earthquakes.head()

    mag magType           time                  place  tsunami parsed_place
0  1.35      ml  1539475168010  9km NE of Aguanga, CA        0   California
1  1.29      ml  1539475129610  9km NE of Aguanga, CA        0   California
2  3.42      ml  1539475062610  8km NE of Aguanga, CA        0   California
3  0.44      ml  1539474978070  9km NE of Aguanga, CA        0   California
4  2.16      md  1539474716050  10km NW of Avenal, CA        0   California

In [45]:
df_earthquakes_jpn = df_earthquakes[(df_earthquakes['place'].str.contains('Japan')) & (df_earthquakes['mag'] >= 4.9) & (df_earthquakes['magType'] == 'mb')]
df_earthquakes_jpn

,mag,magType,time,place,tsunami,parsed_place
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan

# Exercise 2.

Create bins for each full number of earthquake magnitude (for instance, the first bin is (0,1], the second is (1,2], and so on) with the ml magnitude type and count how many are in each bin.

In [46]:
# Filter for 'ml' magnitude type
df_ml = df_earthquakes[df_earthquakes['magType'] == 'ml']

# Create bins for each full number of magnitude
bins = range(0, int(df_ml['mag'].max()) + 2)  # +2 to include the last edge
print(bins)
print(df_ml['mag'].max())

# Creating the labels for the bins
labels = [f"({i},{i+1}]" for i in range(0, int(df_ml['mag'].max()) + 1)]
print(labels)
# Assigning bins to a new column using pd.cut
df_ml['mag_bin'] = pd.cut(df_ml['mag'], bins=bins, labels=labels, right=True)
df_ml.head()
# Count earthquakes in each bin
bin_counts = df_ml['mag_bin'].value_counts().sort_index()
print(bin_counts)

range(0, 7)
5.1
['(0,1]', '(1,2]', '(2,3]', '(3,4]', '(4,5]', '(5,6]']
mag_bin
(0,1]    2207
(1,2]    3105
(2,3]     862
(3,4]     122
(4,5]       2
(5,6]       1
Name: count, dtype: int64

/var/folders/kt/8x_y26sd0zj2rc0xsj2ydy6m0000gn/T/ipykernel_2504/3340074694.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ml['mag_bin'] = pd.cut(df_ml['mag'], bins=bins, labels=labels, right=True)

# Exercise 4.

Build a crosstab with the earthquake data between the tsunami column and the magType column. Rather than showing the frequency count, show the maximum magnitude that was observed for each combination. Put the magnitude type along the columns.

In [47]:
# Creating the crosstab using the pandas crosstab function
pd.crosstab(index=df_earthquakes['tsunami'], columns=df_earthquakes['magType'],  \
            values=df_earthquakes['mag'], aggfunc='max')

magType   mb  mb_lg    md   mh   ml  ms_20    mw  mwb  mwr  mww
tsunami
0        5.6    3.5  4.11  1.1  4.2    NaN  3.83  5.8  4.8  6.0
1        6.1    NaN   NaN  NaN  5.1    5.7  4.41  NaN  NaN  7.5

# Exercise 6.

Create a pivot table of the FAANG data that compares the stocks. Put the ticker in the rows and show the averages of the OHLC and volume traded data.

In [48]:
# Reading the FAANG stock data
df_faang = pd.read_csv('FAANG.csv')
df_faang.head()
# Creating the pivot table using the pandas pivot_table function
pivot_table_faang = pd.pivot_table(df_faang, index='ticker', 
                                   values=['open', 'high', 'low', 'close', 'volume'], 
                                   aggfunc='mean')
pivot_table_faang

              close         high          low         open        volume
ticker
AAPL      47.263357    47.748526    46.795877    47.277859  1.360803e+08
AMZN    1641.726176  1662.839839  1619.840519  1644.072709  5.648994e+06
FB       171.510956   173.613347   169.303148   171.472948  2.765860e+07
GOOG    1113.225134  1125.777606  1101.001658  1113.554101  1.741965e+06
NFLX     319.290319   325.219322   313.187330   319.620558  1.146962e+07

# Exercise 7.

Calculate the z-scores for each numeric column of Amazon’s data (ticker is AMZN) in Q4 2018 using apply().

In [49]:
# Filtering the Amazon data for Q4 2018
df_amzn_q4_2018 = df_faang[(df_faang['ticker'] == 'AMZN') & 
                           (df_faang['date'] >= '2018-10-01') & 
                           (df_faang['date'] <= '2018-12-31')]
# Applying the z-score formula using apply() for the OHLC and volume columns
z_scores_amzn = df_amzn_q4_2018[['open', 'high', 'low', 'close', 'volume']]. \
    apply(lambda x: (x - x.mean()) / x.std())
z_scores_amzn

         open      high       low     close    volume
690  2.337813  2.368006  2.502113  2.385848 -1.630411
691  2.190795  2.227302  2.247433  2.155037 -0.861879
692  2.068570  2.058955  2.139987  2.025489 -0.920345
693  1.850048  1.819474  1.781561  1.722816 -0.126582
694  1.642819  1.628173  1.554416  1.584748 -0.298771
..        ...       ...       ...       ...       ...
748 -2.179582 -2.159820 -2.187566 -2.226185 -0.141238
749 -2.026617 -1.611714 -1.810493 -1.339674  1.123063
750 -1.456521 -1.641276 -1.626703 -1.404343  0.849827
751 -1.328549 -1.325261 -1.231588 -1.289951  0.496102
752 -1.078283 -1.273456 -0.975763 -1.122691 -0.246405

[63 rows x 5 columns]

# Exercise 10.

The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data through September 18, 2020. Complete the following tasks to practice the skills you've learned up to this point in the book:

## 1. Prepare the data

### a. Read in the data in the covid19_cases.csv file.

In [50]:
df_covid19 = pd.read_csv('covid19_cases.csv')
df_covid19.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
1,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
2,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
3,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
4,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159

## b. Create a date column by parsing the dateRep column into a datetime.

In [51]:
# Adding a new column dateRep_dt by parsing the dateRep column into a datetime
df_covid19['dateRep_dt'] = df_covid19['dateRep'].\
    apply(lambda x: pd.to_datetime(x, format='%d/%m/%Y')) 
df_covid19.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,dateRep_dt
0,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645,2020-09-19
1,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155,2020-09-18
2,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446,2020-09-17
3,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649,2020-09-16
4,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159,2020-09-15

### c. Set the date column as the index.

In [52]:
# Setting the dateRep_dt column as the index using set_index() function
df_covid19.set_index('dateRep_dt', inplace=True)
df_covid19.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
dateRep_dt,,,,,,,,,,,,
2020-09-19,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
2020-09-18,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
2020-09-17,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
2020-09-16,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
2020-09-15,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159

### d. Use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.

In [53]:
df_covid19.replace({'United_States_of_America': 'USA', 'United_Kingdom': 'UK'}, inplace=True)

In [54]:
# Checking if the replacements were successful for USA
df_covid19[df_covid19['countriesAndTerritories'].isin(['USA'])].head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
dateRep_dt,,,,,,,,,,,,
2020-09-19,19/09/2020,19,9,2020,50209,956,USA,US,USA,329064917.0,America,158.917275
2020-09-18,18/09/2020,18,9,2020,43567,831,USA,US,USA,329064917.0,America,159.179230
2020-09-17,17/09/2020,17,9,2020,24598,865,USA,US,USA,329064917.0,America,156.955352
2020-09-16,16/09/2020,16,9,2020,51473,1407,USA,US,USA,329064917.0,America,161.257239
2020-09-15,15/09/2020,15,9,2020,34841,451,USA,US,USA,329064917.0,America,159.180445

In [55]:
# Checking if the replacements were successful for UK
df_covid19[df_covid19['countriesAndTerritories'].isin(['UK'])].head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
dateRep_dt,,,,,,,,,,,,
2020-09-19,19/09/2020,19,9,2020,4322,27,UK,UK,GBR,66647112.0,Europe,65.396682
2020-09-18,18/09/2020,18,9,2020,3395,21,UK,UK,GBR,66647112.0,Europe,61.822634
2020-09-17,17/09/2020,17,9,2020,3991,20,UK,UK,GBR,66647112.0,Europe,59.331903
2020-09-16,16/09/2020,16,9,2020,3103,27,UK,UK,GBR,66647112.0,Europe,55.606310
2020-09-15,15/09/2020,15,9,2020,2621,9,UK,UK,GBR,66647112.0,Europe,52.893515

## 2. For the five countries with the most cases (cumulative), find the day with the largest number of cases.

In [56]:
df_covid19.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
dateRep_dt,,,,,,,,,,,,
2020-09-19,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
2020-09-18,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
2020-09-17,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
2020-09-16,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
2020-09-15,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159

In [57]:
# Finding the five countries with the most cumulative cases
top_five_coutries = df_covid19.groupby('countriesAndTerritories')['cases'].sum().nlargest(5).index
top_five_coutries

Index(['USA', 'India', 'Brazil', 'Russia', 'Peru'], dtype='object', name='countriesAndTerritories')

In [58]:
# Find the day with the largest number of cases for these top five countries (identified above)
df_covid19[df_covid19['countriesAndTerritories'].isin(top_five_coutries)]. \
    groupby('countriesAndTerritories').cases.idxmax()

countriesAndTerritories
Brazil   2020-07-30
India    2020-09-17
Peru     2020-08-17
Russia   2020-07-18
USA      2020-07-25
Name: cases, dtype: datetime64[ns]

## 3. Find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.

In [59]:
# Filtering the dataframe for only the top five countries
df_cv19_top5_countries = df_covid19[df_covid19['countriesAndTerritories'].isin(top_five_coutries)]
df_cv19_top5_countries.countriesAndTerritories.unique()

array(['Brazil', 'India', 'Peru', 'Russia', 'USA'], dtype=object)

In [60]:
df_cv19_top5_countries_grp = df_cv19_top5_countries.groupby(['countriesAndTerritories', pd.Grouper(freq='1d')]).cases.sum()
df_cv19_top5_countries_grp

countriesAndTerritories  dateRep_dt
Brazil                   2019-12-31        0
                         2020-01-01        0
                         2020-01-02        0
                         2020-01-03        0
                         2020-01-04        0
                                       ...
USA                      2020-09-15    34841
                         2020-09-16    51473
                         2020-09-17    24598
                         2020-09-18    43567
                         2020-09-19    50209
Name: cases, Length: 1251, dtype: int64

In [61]:
# Unstacking the grouped dataframe, 
# calculating the daily difference, 
# applying a 7-day rolling mean, 
# and filtering for the last week

df_cv19_top5_countries_grp.unstack(0).diff().rolling(7).mean().last('1W')

/var/folders/kt/8x_y26sd0zj2rc0xsj2ydy6m0000gn/T/ipykernel_2504/1197604543.py:6: FutureWarning: last is deprecated and will be removed in a future version. Please create a mask and filter using `.loc` instead
  df_cv19_top5_countries_grp.unstack(0).diff().rolling(7).mean().last('1W')

countriesAndTerritories,Brazil,India,Peru,Russia,USA
dateRep_dt,,,,,
2020-09-14,35.285714,181.285714,73.142857,36.285714,473.714286
2020-09-15,697.428571,1142.857143,377.571429,46.285714,1513.000000
2020-09-16,3196.285714,59.571429,-65.000000,61.428571,3478.714286
2020-09-17,143.428571,308.428571,-29.428571,810.000000,-1047.000000
2020-09-18,-607.714286,-18.142857,-227.571429,-688.428571,865.714286
2020-09-19,-560.142857,-604.714286,-41.285714,57.285714,306.857143

## 4. Find the first date that each country other than China had cases.

In [62]:
# Filtering out China and removing the rows with zero cases,
# Finding the first date that each country had cases
df_covid19[(df_covid19['countriesAndTerritories'] !='China') & (df_covid19["cases"]!=0) ].\
    groupby('countriesAndTerritories').\
    cases.idxmin()

countriesAndTerritories
Afghanistan      2020-08-26
Albania          2020-05-20
Algeria          2020-03-14
Andorra          2020-08-09
Angola           2020-06-09
                    ...
Vietnam          2020-09-12
Western_Sahara   2020-06-20
Yemen            2020-09-19
Zambia           2020-06-15
Zimbabwe         2020-05-12
Name: cases, Length: 209, dtype: datetime64[ns]

## 5. Rank the countries by cumulative cases using percentiles.

In [63]:
# Grouping by countries and ranking by cumulative cases using percentiles

df_covid19_rank=df_covid19.groupby("countriesAndTerritories").cases.sum().rank(pct=True)
df_covid19_rank
#sort the data in descending order
df_covid19_rank.sort_values(ascending=False)

countriesAndTerritories
USA                            1.000000
India                          0.995238
Brazil                         0.990476
Russia                         0.985714
Peru                           0.980952
                                 ...
Greenland                      0.023810
Montserrat                     0.016667
Falkland_Islands_(Malvinas)    0.016667
Holy_See                       0.009524
Anguilla                       0.004762
Name: cases, Length: 210, dtype: float64