*****
*  DSC 530
*  Week 1 & 2
*  Rethish Plappuzha Sreedharan Nair
*****

# Chapter 3, Exercise 1

We want to look at data for the Facebook, Apple, Amazon, Netflix, and Google (FAANG) stocks, but we were given each as a separate CSV file. Combine them into a single file and store the dataframe of the FAANG data as faang for the rest of the exercises:

In [1]:
# importing the required libraries
import pandas as pd

In [2]:
# Reading the files into their own data set
df_fb = pd.read_csv('./data/fb.csv')
df_app1 = pd.read_csv('./data/aapl.csv')
df_amz = pd.read_csv('./data/amzn.csv')
df_goog = pd.read_csv('./data/goog.csv')
df_nflx = pd.read_csv('./data/nflx.csv')

In [10]:
# Adding a Ticker Column
df_fb['ticker']='META'
df_app1['ticker']='AAPL'
df_amz['ticker']='AMZN'
df_goog['ticker']='GOOG'
df_nflx['ticker']='NFLX'

In [35]:
# checking the data frames
print(df_fb.shape)
df_fb.head(3)

(251, 7)

         date        high         low        open       close    volume ticker
0  2018-01-02  181.580002  177.550003  177.679993  181.419998  18151900   META
1  2018-01-03  184.779999  181.330002  181.880005  184.669998  16886600   META
2  2018-01-04  186.210007  184.100006  184.899994  184.330002  13880900   META

In [34]:
# checking the data frames
print(df_app1.shape)
df_app1.head(3)

(251, 7)

         date       high        low       open      close       volume ticker
0  2018-01-02  43.075001  42.314999  42.540001  43.064999  102223600.0   AAPL
1  2018-01-03  43.637501  42.990002  43.132500  43.057499  118071600.0   AAPL
2  2018-01-04  43.367500  43.020000  43.134998  43.257500   89738400.0   AAPL

In [33]:
# checking the data frames
print(df_amz.shape)
df_amz.head(3)

(251, 7)

,date,high,low,open,close,volume,ticker
0,2018-01-02,1190.000000,1170.510010,1172.000000,1189.010010,2694500,AMZN
1,2018-01-03,1205.489990,1188.300049,1188.300049,1204.199951,3108800,AMZN
2,2018-01-04,1215.869995,1204.660034,1205.000000,1209.589966,3022100,AMZN

In [32]:
# checking the data frames
print(df_nflx.shape)
df_nflx.head(3)

(251, 7)

         date        high         low        open       close    volume ticker
0  2018-01-02  201.649994  195.419998  196.100006  201.070007  10966900   NFLX
1  2018-01-03  206.210007  201.500000  202.050003  205.050003   8591400   NFLX
2  2018-01-04  207.050003  204.000000  206.199997  205.630005   6029600   NFLX

In [31]:
# checking the data frames
print(df_goog.shape)
df_goog.head(3)

(251, 7)

,date,high,low,open,close,volume,ticker
0,2018-01-02,1066.939941,1045.229980,1048.339966,1065.000000,1237600,GOOG
1,2018-01-03,1086.290039,1063.209961,1064.310059,1082.479980,1430200,GOOG
2,2018-01-04,1093.569946,1084.001953,1088.000000,1086.400024,1004600,GOOG

In [22]:
# Appending all the data frames to a single dataframe
df_faang = pd.concat([df_fb,df_app1,df_amz,df_nflx,df_goog])
df_faang.groupby(['ticker']).date.count()

ticker
AAPL    251
AMZN    251
GOOG    251
META    251
NFLX    251
Name: date, dtype: int64

In [36]:
df_faang.to_csv('faang.csv', index=False)

# Chapter 3, Exercise 2

With faang, use type conversion to cast the values of the date column into datetimes and the volume column into integers. Then, sort by date and ticker.

In [1]:
# importing the required libraries
import pandas as pd

In [45]:
# Reading the faang.csv and creating a data frame
df_faang=pd.read_csv('./faang.csv')
print(df_faang.shape)
df_faang.head(3)

(1255, 7)

,date,high,low,open,close,volume,ticker
0,2018-01-02,181.580002,177.550003,177.679993,181.419998,18151900.0,META
1,2018-01-03,184.779999,181.330002,181.880005,184.669998,16886600.0,META
2,2018-01-04,186.210007,184.100006,184.899994,184.330002,13880900.0,META

In [46]:
# Converting the data type of the column date to datetime
print("Data type of the column 'date' before conversion", df_faang['date'].dtypes) 
df_faang['date'] = pd.to_datetime(df_faang['date'], format='%Y-%m-%d')
print("Data type of the column 'date' after conversion",df_faang['date'].dtypes)

Data type of the column 'date' before conversion object
Data type of the column 'date' after conversion datetime64[ns]

In [48]:
# Converting the data type of the column date to datetime
print("Data type of the column 'volume' before conversion", df_faang['volume'].dtypes) 
df_faang['volume'] = df_faang['volume'].astype(int)
print("Data type of the column 'volume' after conversion",df_faang['volume'].dtypes)

Data type of the column 'volume' before conversion float64
Data type of the column 'volume' after conversion int64

In [49]:
# Printing the values after formatting 
df_faang.head(3)

        date        high         low        open       close    volume ticker
0 2018-01-02  181.580002  177.550003  177.679993  181.419998  18151900   META
1 2018-01-03  184.779999  181.330002  181.880005  184.669998  16886600   META
2 2018-01-04  186.210007  184.100006  184.899994  184.330002  13880900   META

In [50]:
# Implementing the sorting with fields date and ticker
df_faang=df_faang.sort_values(['date','ticker'], ascending=[True, True])
df_faang.head()

,date,high,low,open,close,volume,ticker
251,2018-01-02,43.075001,42.314999,42.540001,43.064999,102223600,AAPL
502,2018-01-02,1190.000000,1170.510010,1172.000000,1189.010010,2694500,AMZN
1004,2018-01-02,1066.939941,1045.229980,1048.339966,1065.000000,1237600,GOOG
0,2018-01-02,181.580002,177.550003,177.679993,181.419998,18151900,META
753,2018-01-02,201.649994,195.419998,196.100006,201.070007,10966900,NFLX

# Chapter 3, Exercise 3

Find the seven rows in faang with the lowest value for volume.

In [56]:
# importing the required libraries
import pandas as pd

In [60]:
# Reading the faang.csv and creating a data frame
df_faang=pd.read_csv('./faang.csv')
# Converting the column volume to int
df_faang['volume'] = df_faang['volume'].astype(int)

# sorting the smallest to largest and returning the first seven rows
df_faang = df_faang.nsmallest(7, 'volume')
print(df_faang.sort_values(['volume']))

            date         high          low         open        close  volume  \
1130  2018-07-03  1135.819946  1100.020020  1135.819946  1102.890015  679000
1230  2018-11-23  1037.589966  1022.398987  1030.000000  1023.880005  691500
1103  2018-05-24  1080.469971  1066.150024  1079.000000  1079.239990  766800
1134  2018-07-10  1159.589966  1149.589966  1156.979980  1152.839966  798400
1156  2018-08-09  1255.541992  1246.010010  1249.900024  1249.099976  848600
1163  2018-08-20  1211.000000  1194.625977  1205.020020  1207.770020  870800
1165  2018-08-22  1211.839966  1199.000000  1200.000000  1207.329956  887400

     ticker
1130   GOOG
1230   GOOG
1103   GOOG
1134   GOOG
1156   GOOG
1163   GOOG
1165   GOOG

# Chapter 3, Exercise 4

Right now, the data is somewhere between long and wide format. Use melt() to make it completely long format. Hint: date and ticker are our ID variables (they uniquely identify each row). We need to melt the rest so that we don't have separate columns for open, high, low, close, and volume.

In [56]:
# importing the required libraries
import pandas as pd

In [68]:
df_faang=pd.read_csv('./faang.csv')
df_faang

,date,high,low,open,close,volume,ticker
0,2018-01-02,181.580002,177.550003,177.679993,181.419998,18151900.0,META
1,2018-01-03,184.779999,181.330002,181.880005,184.669998,16886600.0,META
2,2018-01-04,186.210007,184.100006,184.899994,184.330002,13880900.0,META
3,2018-01-05,186.899994,184.929993,185.589996,186.850006,13574500.0,META
4,2018-01-08,188.899994,186.330002,187.199997,188.279999,17994700.0,META
...,...,...,...,...,...,...,...
1250,2018-12-24,1003.539978,970.109985,973.900024,976.219971,1590300.0,GOOG
1251,2018-12-26,1040.000000,983.000000,989.010010,1039.459961,2373300.0,GOOG
1252,2018-12-27,1043.890015,997.000000,1017.150024,1043.880005,2109800.0,GOOG
1253,2018-12-28,1055.560059,1033.099976,1049.619995,1037.079956,1414800.0,GOOG
1254,2018-12-31,1052.699951,1023.590027,1050.959961,1035.609985,1493300.0,GOOG

In [69]:

# implementing the melt function 
df_faang_melt = pd.melt(df_faang,
                        id_vars=['date', 'ticker'],
                        value_vars=['high', 'low', 'open', 'close', 'volume'],
                       value_name='Melted_Value')
df_faang_melt.head(10)

         date ticker variable  Melted_Value
0  2018-01-02   META     high    181.580002
1  2018-01-03   META     high    184.779999
2  2018-01-04   META     high    186.210007
3  2018-01-05   META     high    186.899994
4  2018-01-08   META     high    188.899994
5  2018-01-09   META     high    188.800003
6  2018-01-10   META     high    187.889999
7  2018-01-11   META     high    188.399994
8  2018-01-12   META     high    181.479996
9  2018-01-16   META     high    181.750000

# Chapter 3, Exercise 5

Suppose we found out that on July 26, 2018 there was a glitch in how the data was recorded. How should we handle this? Note that there is no coding required for this exercise.

In [56]:
# importing the required libraries
import pandas as pd

In [70]:
df_faang = pd.read_csv('faang.csv')

In [71]:

df_faang['date'] = pd.to_datetime(df_faang['date'], format='%Y-%m-%d')

In [88]:
df_july = df_faang[ df_faang['date']>'2018-06-30'][df_faang['date']<'2018-08-01']
# Checking the daily count of records, and we can see the count is matching with the previous days
df_july.groupby(['date']).date.count()

/var/folders/kt/8x_y26sd0zj2rc0xsj2ydy6m0000gn/T/ipykernel_72812/329601193.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_july = df_faang[ df_faang['date']>'2018-06-30'][df_faang['date']<'2018-08-01']

date
2018-07-02    5
2018-07-03    5
2018-07-05    5
2018-07-06    5
2018-07-09    5
2018-07-10    5
2018-07-11    5
2018-07-12    5
2018-07-13    5
2018-07-16    5
2018-07-17    5
2018-07-18    5
2018-07-19    5
2018-07-20    5
2018-07-23    5
2018-07-24    5
2018-07-25    5
2018-07-26    5
2018-07-27    5
2018-07-30    5
2018-07-31    5
Name: date, dtype: int64

In [96]:
#Checking the values from previous and after four days from 2018-july-26
df_july_week4 = df_faang[ df_faang['date']>'2018-07-22'][df_faang['date']<'2018-07-30']
#df_july_week4[ df_july_week4['ticker'] == 'META'].sort_values(['date'])  ## Checking the META 
#df_july_week4[ df_july_week4['ticker'] == 'AAPL'].sort_values(['date'])  ## Checking the AAPL 
#df_july_week4[ df_july_week4['ticker'] == 'AMZN'].sort_values(['date'])  ## Checking the AMZN 
#df_july_week4[ df_july_week4['ticker'] == 'AMZN'].sort_values(['date'])  ## Checking the AMZN 
#df_july_week4[ df_july_week4['ticker'] == 'GOOG'].sort_values(['date'])  ## Checking the GOOG 

# After analyzing the data from each company for the week spanning 7/26, we can see the values 
# are looking good.

/var/folders/kt/8x_y26sd0zj2rc0xsj2ydy6m0000gn/T/ipykernel_72812/1028400209.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_july_week4 = df_faang[ df_faang['date']>'2018-07-22'][df_faang['date']<'2018-07-30']

,date,high,low,open,close,volume,ticker
1143,2018-07-23,1206.489990,1181.000000,1181.010010,1205.500000,2619200.0,GOOG
1144,2018-07-24,1266.000000,1235.560059,1262.589966,1248.079956,3318200.0,GOOG
1145,2018-07-25,1265.859985,1239.130005,1239.130005,1263.699951,2127800.0,GOOG
1146,2018-07-26,1269.770996,1249.020020,1251.000000,1268.329956,2405600.0,GOOG
1147,2018-07-27,1273.890015,1231.000000,1271.000000,1238.500000,2130600.0,GOOG

# Chapter 3, Exercise 6

The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data from January 1, 2020 through September 18, 2020. Clean and pivot the data so that it is in wide format:

## Exercise 6.a
Read in the covid19_cases.csv file.

In [56]:
# importing the required libraries
import pandas as pd

In [109]:
# Reading the CSV File
df_covid_19 = pd.read_csv('./covid19_data.csv')
df_covid_19.head(5)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658

## Exercise 6.b

Create a date column using the data in the dateRep column and the pd.to_datetime() function.

In [110]:
# Adding a new date field by converting the dateRep column to date time format
df_covid_19['date'] = pd.to_datetime(df_covid_19['dateRep'], format='%d/%m/%Y')
df_covid_19.head(10)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,date
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779,2020-12-14
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776,2020-12-13
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768,2020-12-12
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266,2020-12-11
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658,2020-12-10
5,09/12/2020,9,12,2020,135,13,Afghanistan,AF,AFG,38041757.0,Asia,6.963401,2020-12-09
6,08/12/2020,8,12,2020,200,6,Afghanistan,AF,AFG,38041757.0,Asia,7.094835,2020-12-08
7,07/12/2020,7,12,2020,210,26,Afghanistan,AF,AFG,38041757.0,Asia,7.215755,2020-12-07
8,06/12/2020,6,12,2020,234,10,Afghanistan,AF,AFG,38041757.0,Asia,7.326160,2020-12-06
9,05/12/2020,5,12,2020,235,18,Afghanistan,AF,AFG,38041757.0,Asia,7.115865,2020-12-05

## Exercise 6.c

Set the date column as the index and sort the index.

In [111]:
# setting the date as the index column and sorting 
df_covid_19  = df_covid_19.set_index('date', drop=False).sort_index()
df_covid_19

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,date
date,,,,,,,,,,,,,
2019-12-31,31/12/2019,31,12,2019,0,0,Iraq,IQ,IRQ,39309789.0,Asia,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Netherlands,NL,NLD,17282163.0,Europe,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Israel,IL,ISR,8519373.0,Asia,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,New_Zealand,NZ,NZL,4783062.0,Oceania,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Dominican_Republic,DO,DOM,10738957.0,America,NaN,2019-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-14,14/12/2020,14,12,2020,316,1,Honduras,HN,HND,9746115.0,America,66.395687,2020-12-14
2020-12-14,14/12/2020,14,12,2020,0,0,Holy_See,VA,VAT,815.0,Europe,0.000000,2020-12-14
2020-12-14,14/12/2020,14,12,2020,74,1,Haiti,HT,HTI,11263079.0,America,2.672449,2020-12-14
2020-12-14,14/12/2020,14,12,2020,6189,166,Indonesia,ID,IDN,270625567.0,Asia,30.874393,2020-12-14
2020-12-14,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779,2020-12-14

## Exercise 6.d

Replace all occurrences of United_States_of_America and United_Kingdom with USA and UK, respectively. Hint: the replace() method can be run on the dataframe as a whole.

In [131]:
df_covid_19

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,date
date,,,,,,,,,,,,,
2019-12-31,31/12/2019,31,12,2019,0,0,Iraq,IQ,IRQ,39309789.0,Asia,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Netherlands,NL,NLD,17282163.0,Europe,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Israel,IL,ISR,8519373.0,Asia,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,New_Zealand,NZ,NZL,4783062.0,Oceania,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Dominican_Republic,DO,DOM,10738957.0,America,NaN,2019-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-14,14/12/2020,14,12,2020,316,1,Honduras,HN,HND,9746115.0,America,66.395687,2020-12-14
2020-12-14,14/12/2020,14,12,2020,0,0,Holy_See,VA,VAT,815.0,Europe,0.000000,2020-12-14
2020-12-14,14/12/2020,14,12,2020,74,1,Haiti,HT,HTI,11263079.0,America,2.672449,2020-12-14
2020-12-14,14/12/2020,14,12,2020,6189,166,Indonesia,ID,IDN,270625567.0,Asia,30.874393,2020-12-14
2020-12-14,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779,2020-12-14

In [136]:
## Replacing the United_States_of_America and United_Kingdom with USA and UK

df_covid_19['countriesAndTerritories']=df_covid_19['countriesAndTerritories'].replace(
    'United_States_of_America', 'USA')

df_covid_19['countriesAndTerritories']=df_covid_19['countriesAndTerritories'].replace(
    'United_Kingdom', 'UK')

df_covid_19[df_covid_19['countriesAndTerritories'].isin(['USA','UK'])]

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,date
date,,,,,,,,,,,,,
2019-12-31,31/12/2019,31,12,2019,0,0,USA,US,USA,329064917.0,America,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,UK,UK,GBR,66647112.0,Europe,NaN,2019-12-31
2020-01-01,01/01/2020,1,1,2020,0,0,USA,US,USA,329064917.0,America,NaN,2020-01-01
2020-01-01,01/01/2020,1,1,2020,0,0,UK,UK,GBR,66647112.0,Europe,NaN,2020-01-01
2020-01-02,02/01/2020,2,1,2020,0,0,UK,UK,GBR,66647112.0,Europe,NaN,2020-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-12,12/12/2020,12,12,2020,21672,424,UK,UK,GBR,66647112.0,Europe,330.327892,2020-12-12
2020-12-13,13/12/2020,13,12,2020,216017,2315,USA,US,USA,329064917.0,America,857.089241,2020-12-13
2020-12-13,13/12/2020,13,12,2020,21501,520,UK,UK,GBR,66647112.0,Europe,338.775370,2020-12-13
2020-12-14,14/12/2020,14,12,2020,189723,1340,USA,US,USA,329064917.0,America,873.211592,2020-12-14
2020-12-14,14/12/2020,14,12,2020,18447,144,UK,UK,GBR,66647112.0,Europe,348.216139,2020-12-14

## Exercise 6.e

Using the countriesAndTerritories column, filter the cleaned COVID-19 cases data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.

In [142]:
# Filtering the data for the specific countries
df_covid_19_filtered = df_covid_19[df_covid_19['countriesAndTerritories'].isin(['USA','UK',
    'Argentina', 'Brazil', 'China', 'Colombia', 'India', 'Italy', 'Mexico', 'Peru', 'Russia', 
    'Spain', 'Turkey'])]
df_covid_19_filtered

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,date
date,,,,,,,,,,,,,
2019-12-31,31/12/2019,31,12,2019,0,0,USA,US,USA,3.290649e+08,America,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Brazil,BR,BRA,2.110495e+08,America,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Spain,ES,ESP,4.693706e+07,Europe,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Italy,IT,ITA,6.035955e+07,Europe,NaN,2019-12-31
2019-12-31,31/12/2019,31,12,2019,0,0,Russia,RU,RUS,1.458723e+08,Europe,NaN,2019-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-14,14/12/2020,14,12,2020,21825,279,Brazil,BR,BRA,2.110495e+08,America,278.234228,2020-12-14
2020-12-14,14/12/2020,14,12,2020,8608,249,Mexico,MX,MEX,1.275755e+08,America,112.069298,2020-12-14
2020-12-14,14/12/2020,14,12,2020,29136,222,Turkey,TR,TUR,8.200388e+07,Europe,499.220269,2020-12-14
2020-12-14,14/12/2020,14,12,2020,17937,484,Italy,IT,ITA,6.035955e+07,Europe,428.323301,2020-12-14
2020-12-14,14/12/2020,14,12,2020,27071,336,India,IN,IND,1.366418e+09,Asia,33.109128,2020-12-14

## Exercise 6.f

Pivot the data so that the index contains the dates, the columns contain the country names, and the values are the case counts (the cases column). Be sure to fill in NaN values with 0.

In [144]:
# Dropping the duplicate column date as date is index and another column
df_covid_19_filtered_datedroped = df_covid_19_filtered.drop('date', axis=1)
# Creating the pivot table
df_covid_19_filtered_pivot=df_covid_19_filtered_datedroped.pivot_table(
    index='date',columns=['countriesAndTerritories'],
    values=['cases'],margins=False).fillna(0) 
df_covid_19_filtered_pivot

                            cases                                            \
countriesAndTerritories Argentina   Brazil China Colombia    India    Italy
date
2019-12-31                    0.0      0.0  27.0      0.0      0.0      0.0
2020-01-01                    0.0      0.0   0.0      0.0      0.0      0.0
2020-01-02                    0.0      0.0   0.0      0.0      0.0      0.0
2020-01-03                    0.0      0.0  17.0      0.0      0.0      0.0
2020-01-04                    0.0      0.0   0.0      0.0      0.0      0.0
...                           ...      ...   ...      ...      ...      ...
2020-12-10                 5303.0  53453.0  12.0   7523.0  31521.0  12755.0
2020-12-11                 6994.0  53347.0  15.0   7778.0  29398.0  16998.0
2020-12-12                 7112.0  54428.0  13.0   8998.0  30006.0  18726.0
2020-12-13                 5274.0  43900.0  24.0   8163.0  30254.0  19902.0
2020-12-14                 3558.0  21825.0  12.0   8702.0  27071.0  17937.0

                                                                              \
countriesAndTerritories   Mexico    Peru   Russia    Spain   Turkey       UK
date
2019-12-31                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-01                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-02                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-03                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-04                   0.0     0.0      0.0      0.0      0.0      0.0
...                          ...     ...      ...      ...      ...      ...
2020-12-10               21974.0   691.0  26190.0   7955.0  31712.0  16578.0
2020-12-11               11897.0  1799.0  27927.0  10519.0  30424.0  20964.0
2020-12-12               12253.0  1832.0  28585.0      0.0      0.0  21672.0
2020-12-13               12057.0  2102.0  28137.0      0.0  32106.0  21501.0
2020-12-14                8608.0  1928.0  28080.0      0.0  29136.0  18447.0


countriesAndTerritories       USA
date
2019-12-31                    0.0
2020-01-01                    0.0
2020-01-02                    0.0
2020-01-03                    0.0
2020-01-04                    0.0
...                           ...
2020-12-10               220025.0
2020-12-11               224680.0
2020-12-12               234633.0
2020-12-13               216017.0
2020-12-14               189723.0

[350 rows x 13 columns]

In [146]:
# Pivot basic method
df_covid19_pivot=df_covid_19_filtered.pivot(index='date',columns=['countriesAndTerritories'],values=['cases']).fillna(0) 
df_covid19_pivot

                            cases                                            \
countriesAndTerritories Argentina   Brazil China Colombia    India    Italy
date
2019-12-31                    0.0      0.0  27.0      0.0      0.0      0.0
2020-01-01                    0.0      0.0   0.0      0.0      0.0      0.0
2020-01-02                    0.0      0.0   0.0      0.0      0.0      0.0
2020-01-03                    0.0      0.0  17.0      0.0      0.0      0.0
2020-01-04                    0.0      0.0   0.0      0.0      0.0      0.0
...                           ...      ...   ...      ...      ...      ...
2020-12-10                 5303.0  53453.0  12.0   7523.0  31521.0  12755.0
2020-12-11                 6994.0  53347.0  15.0   7778.0  29398.0  16998.0
2020-12-12                 7112.0  54428.0  13.0   8998.0  30006.0  18726.0
2020-12-13                 5274.0  43900.0  24.0   8163.0  30254.0  19902.0
2020-12-14                 3558.0  21825.0  12.0   8702.0  27071.0  17937.0

                                                                              \
countriesAndTerritories   Mexico    Peru   Russia    Spain   Turkey       UK
date
2019-12-31                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-01                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-02                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-03                   0.0     0.0      0.0      0.0      0.0      0.0
2020-01-04                   0.0     0.0      0.0      0.0      0.0      0.0
...                          ...     ...      ...      ...      ...      ...
2020-12-10               21974.0   691.0  26190.0   7955.0  31712.0  16578.0
2020-12-11               11897.0  1799.0  27927.0  10519.0  30424.0  20964.0
2020-12-12               12253.0  1832.0  28585.0      0.0      0.0  21672.0
2020-12-13               12057.0  2102.0  28137.0      0.0  32106.0  21501.0
2020-12-14                8608.0  1928.0  28080.0      0.0  29136.0  18447.0


countriesAndTerritories       USA
date
2019-12-31                    0.0
2020-01-01                    0.0
2020-01-02                    0.0
2020-01-03                    0.0
2020-01-04                    0.0
...                           ...
2020-12-10               220025.0
2020-12-11               224680.0
2020-12-12               234633.0
2020-12-13               216017.0
2020-12-14               189723.0

[350 rows x 13 columns]